import { apiBranchQR } from "../../services/apiBranchQR";
import { qrCodeUtils } from "../../src/lib/qr-code-generator";
import { Branch } from "../../src/types/feedback";

// Mock the feature flags
jest.mock("../../src/lib/feature-flags", () => ({
  isFeatureEnabled: jest.fn(() => true),
}));

// Mock Supabase
jest.mock("../../services/supabase", () => ({
  from: jest.fn(() => ({
    select: jest.fn(() => ({
      eq: jest.fn(() => ({
        single: jest.fn(() => ({
          data: {
            id: "test-branch-id",
            name_ar: "فرع تجريبي",
            name_en: "Test Branch",
            address_ar: "عنوان تجريبي",
            address_en: "Test Address",
            phone: "123456789",
            created_at: "2024-01-01T00:00:00Z",
          },
          error: null,
        })),
      })),
    })),
    insert: jest.fn(() => ({
      select: jest.fn(() => ({
        single: jest.fn(() => ({
          data: {
            id: "test-qr-id",
            branch_id: "test-branch-id",
            qr_code_url: "data:image/png;base64,test-qr-code",
            qr_code_metadata: {
              branch_id: "test-branch-id",
              branch_name: "Test Branch",
              survey_url:
                "http://localhost:3000/feedback-survey/test-branch-id",
              generated_at: "2024-01-01T00:00:00Z",
              version: "1.0",
            },
            created_at: "2024-01-01T00:00:00Z",
            updated_at: "2024-01-01T00:00:00Z",
          },
          error: null,
        })),
      })),
    })),
  })),
}));

describe("QR Code Generation", () => {
  const mockBranch: Branch = {
    id: "test-branch-id",
    name_ar: "فرع تجريبي",
    name_en: "Test Branch",
    address_ar: "عنوان تجريبي",
    address_en: "Test Address",
    phone: "123456789",
    created_at: "2024-01-01T00:00:00Z",
  };

  describe("QR Code Utils", () => {
    it("should generate survey URL correctly", () => {
      const surveyUrl = qrCodeUtils.generateBranchQRCode(mockBranch);
      expect(surveyUrl).toBeDefined();
    });

    it("should generate QR code metadata correctly", () => {
      const surveyUrl = "http://localhost:3000/feedback-survey/test-branch-id";
      const metadata = {
        branch_id: mockBranch.id,
        branch_name: mockBranch.name_en || mockBranch.name_ar,
        survey_url: surveyUrl,
        generated_at: expect.any(String),
        version: "1.0",
      };

      expect(metadata.branch_id).toBe(mockBranch.id);
      expect(metadata.branch_name).toBe(mockBranch.name_en);
      expect(metadata.survey_url).toBe(surveyUrl);
    });
  });

  describe("API Branch QR", () => {
    it("should generate QR code for a branch", async () => {
      const qrCode = await apiBranchQR.generateQRCode("test-branch-id");

      expect(qrCode).toBeDefined();
      expect(qrCode.branch_id).toBe("test-branch-id");
      expect(qrCode.qr_code_url).toContain("data:image/png;base64");
      expect(qrCode.qr_code_metadata).toBeDefined();
    });

    it("should get QR code for a branch", async () => {
      const qrCode = await apiBranchQR.getBranchQRCode("test-branch-id");

      expect(qrCode).toBeDefined();
      expect(qrCode?.branch_id).toBe("test-branch-id");
    });

    it("should get QR codes for multiple branches", async () => {
      const qrCodes = await apiBranchQR.getQRCodesForBranches([
        "test-branch-id",
      ]);

      expect(Array.isArray(qrCodes)).toBe(true);
      expect(qrCodes.length).toBeGreaterThan(0);
    });

    it("should delete QR code for a branch", async () => {
      await expect(
        apiBranchQR.deleteBranchQRCode("test-branch-id")
      ).resolves.not.toThrow();
    });
  });

  describe("QR Code URL Structure", () => {
    it("should generate correct survey URL format", () => {
      const baseUrl =
        process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
      const expectedUrl = `${baseUrl}/feedback-survey/${mockBranch.id}`;

      // This would be the actual URL generated by the system
      expect(expectedUrl).toMatch(
        /^https?:\/\/.+\/feedback-survey\/[a-zA-Z0-9-]+$/
      );
    });
  });
});
